---
apiVersion: v1
kind: Service
metadata:
  name: sensu
  namespace: sensu-system
spec:
  selector:
    app: sensu
  clusterIP: None
  ports:
  - name: sensu-etcd-client
    port: 2379
  - name: sensu-etcd-server
    port: 2380

---
apiVersion: v1
kind: Service
metadata:
  name: sensu-lb
  namespace: sensu-system
spec:
  selector:
    app: sensu
  type: LoadBalancer
  ports:
  - name: sensu-api
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: sensu-transport
    protocol: TCP
    port: 8081
    targetPort: 8081
  - name: sensu-webui
    protocol: TCP
    port: 80
    targetPort: 3000
